### ISSUE TITLE
Non specified items stop a demo from parsing

### ISSUE THREAD

**Issue by JimmyWoodhouse** [source-engine-discord/SourceEngine.Demo#4]
{"The given key 'CItem_Healthshot | DT_Item_Healthshot' was not present in the dictionary."}

Assumed it would be added similar to this but it seems not: https://github.com/source-engine-discord/SourceEngine.Demo/commit/3d3bb57518e1dfbc976fe6bc1b54ad5c2d9056d6

It should probably try catch so that it just ignored stuff it does not know of

**Comment by JimmyWoodhouse** [comment]
Demo that breaks: 11_27_2020_Wyitica_casual.dem

**Comment by MarkKoz** [comment]
Fixed by 6c37ee19da393acac4fb539070decbe5b0733cd5
