### ISSUE TITLE
Fail to parse demo file. Simple with bots, and exit by quit command. Latest csgo.

### ISSUE THREAD

**Issue by 2020karaulov2020** [source-engine-discord/SourceEngine.Demo#7]
Fail to parse demo file. Simple with bots, and exit by quit command. Latest csgo.

[demo_csgo_test.zip](https://github.com/source-engine-discord/SourceEngine.Demo/files/5744131/demo_csgo_test.zip)

**Comment by JamesT-W** [comment]
Hey, could you record a new demo and see if you have the same issue? It looks like the demo itself might be corrupt when debugging the issue. Also, when watching it in csgo it shows the length of the demo in ticks as being -4785, and as soon as the demo finishes playing it crashes the game (tried it twice). Let me know if a new demo recording fixes it or not!
![image](https://user-images.githubusercontent.com/17306057/103250459-d04d7e80-496b-11eb-9ad8-8ac81efad468.png)

**Comment by JamesT-W** [comment]
This also isn't designed to work for a test demo such as yours, it is designed to solely work for a full game!

**Comment by 2020karaulov2020** [comment]
It support only tv_record , or POV demos too?(record)

**Comment by JamesT-W** [comment]
It was created to work with gotv, I can't say for sure for anything else but there is a good change it will still work! A full match should be recorded though (From warmup to after the match ends)

**Comment by 2020karaulov2020** [comment]
@JamesT-W impossible to fix?

**Comment by JamesT-W** [comment]
@2020karaulov2020 your demo seemed to be corrupt, you should try and record a new one. It is only designed to work for full games too
